In [40]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## The Basics

In [13]:
# a = np.array([1, 2, 3, 4, 5])  # This is normal, without datatype mentioned
a = np.array([1, 2, 3, 4, 5], dtype='int8')
print(a)

[1 2 3 4 5]


In [5]:
b = np.array([[1, 2, 3], [3.2, 5.23, 6.34]])
print(b)

[[1.   2.   3.  ]
 [3.2  5.23 6.34]]


In [7]:
# Get Dimension of an array
a.ndim

1

In [10]:
# Shape of an array
## It tells the rows and cols in (r, c) format
b.shape

(2, 3)

In [14]:
# Get DataType
print(a.dtype)
print(b.dtype)

int8
float64


In [15]:
# Get Size
print(a.itemsize)
print(b.itemsize)

## this tells byte size of each element

1
8


In [16]:
# Get total size
print(a.nbytes)
print(b.nbytes)

5
48


In [18]:
# Get a specific element
print(b[0, 1])

2.0


In [23]:
# Get a specific row
print(b[1, :])
# Get a specific column
print(b[:, 1])

[3.2  5.23 6.34]
[2.   5.23]


## From the documentation

In [47]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
ar = np.arange(2, 25, 2)  # arange(startValue, endValue-excl, step)
print(ar)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [46]:
# For linear spacing
arr = np.linspace(0, 20, num=12) ## linspace(startVal, endVal-incl, total-number-of-elements)
print(arr)

[ 0.          1.81818182  3.63636364  5.45454545  7.27272727  9.09090909
 10.90909091 12.72727273 14.54545455 16.36363636 18.18181818 20.        ]
